name: Update DIX Data Daily

on:
  schedule:
    - cron: '00 15 * * *'  # Runs at 16:45 Europe/Madrid (UTC+2 = 14:45 UTC)
  workflow_dispatch:  # Manual trigger option

jobs:
  update-dix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Download DIX CSV
        run: curl -o DIX.csv https://squeezemetrics.com/monitor/static/DIX.csv

          - name: Commit & Push if Changed
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/caribbel/DIX.git
          git add DIX.csv
          git diff --cached --quiet || git commit -m "Update DIX.csv"
          git push origin main
