name: Update DIX Data Daily

on:
  schedule:
    - cron: '55 10 * * *'  # Runs at 13:00 Valencia time (11:00 UTC)
  workflow_dispatch:

jobs:
  update-dix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # ✅ Disable default token so GH_PAT works

      - name: Download DIX CSV
        run: curl -o DIX.csv https://squeezemetrics.com/monitor/static/DIX.csv

      - name: Commit & Push if Changed
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

          # Set origin with personal access token
          git remote remove origin
          git remote add origin https://x-access-token:$GH_PAT@github.com/caribbel/DIX.git

          git add DIX.csv
          if ! git diff --cached --quiet; then
            git commit -m "Update DIX.csv"
            git push origin main
          else
            echo "No changes to commit."
          fi
